"""add auto_confirm to branches

Revision ID: 13afb2b14af4
Revises: c3788d1fa6e7
Create Date: 2026-05-09 23:13:08.350074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13afb2b14af4'
down_revision: Union[str, None] = 'c3788d1fa6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('auto_confirm', sa.Boolean(), nullable=False, server_default='false', comment='Флаг автоматического подтверждения СФ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'auto_confirm')
    # ### end Alembic commands ###
