"""add transactions

Revision ID: 3c73d1b244b6
Revises: 6fff311a1592
Create Date: 2026-05-12 08:41:23.098629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c73d1b244b6'
down_revision: Union[str, None] = '6fff311a1592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='Внешний ID проводки в АБС'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Дата проводки'),
    sa.Column('transaction_type', sa.Enum('INCOME', 'VAT', name='transactiontype'), nullable=False, comment='Тип: доходная или НДС'),
    sa.Column('status', sa.Enum('NEW', 'MATCHED', 'INVOICED', 'ERROR', name='transactionstatus'), nullable=False, comment='Статус обработки'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Сумма проводки'),
    sa.Column('contract_number', sa.String(length=100), nullable=True, comment='Номер договора'),
    sa.Column('service_code', sa.String(length=50), nullable=True, comment='Код услуги'),
    sa.Column('service_name', sa.String(length=500), nullable=True, comment='Наименование услуги'),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Ставка НДС'),
    sa.Column('link_key', sa.String(length=200), nullable=False, comment='Ключ связки для поиска парной проводки'),
    sa.Column('country_code', sa.String(length=3), nullable=True, comment='Код страны'),
    sa.Column('income_account_id', sa.UUID(), nullable=True, comment='Счёт доходов'),
    sa.Column('vat_account_id', sa.UUID(), nullable=True, comment='Счёт НДС'),
    sa.Column('branch_id', sa.UUID(), nullable=True, comment='Отделение банка'),
    sa.Column('counterparty_id', sa.UUID(), nullable=True, comment='Контрагент'),
    sa.Column('invoice_id', sa.UUID(), nullable=True, comment='Счёт-фактура'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='Исходное сообщение из RabbitMQ (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['income_account_id'], ['income_accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['vat_account_id'], ['vat_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.create_index(op.f('ix_transactions_link_key'), 'transactions', ['link_key'], unique=False)
    op.create_index('ix_transactions_link_key_type', 'transactions', ['link_key', 'transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_link_key_type', table_name='transactions')
    op.drop_index(op.f('ix_transactions_link_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
