"""add invoice_drafts and invoices

Revision ID: 3c999bd4b7f1
Revises: 1eb019a238ff
Create Date: 2026-04-17 09:16:03.545400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c999bd4b7f1'
down_revision: Union[str, None] = '1eb019a238ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.String(length=200), nullable=False, comment='Ключ связывания с проводками'),
    sa.Column('draft_date', sa.Date(), nullable=False, comment='Дата проводки'),
    sa.Column('buyer_name', sa.String(length=500), nullable=True),
    sa.Column('buyer_inn', sa.String(length=12), nullable=True),
    sa.Column('buyer_kpp', sa.String(length=9), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('seller_kpp', sa.String(length=9), nullable=True),
    sa.Column('income_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Сумма комиссии без НДС'),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Ставка НДС'),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Сумма НДС'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Итого с НДС'),
    sa.Column('currency_code', sa.String(length=3), nullable=False, comment='Код валюты (810=RUB)'),
    sa.Column('special_sales_book', sa.Boolean(), nullable=False, comment='Специальная книга продаж'),
    sa.Column('interprice_difference', sa.Boolean(), nullable=False, comment='Межценовая разница'),
    sa.Column('branch_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='invoicedraftstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_drafts_operation_id'), 'invoice_drafts', ['operation_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False, comment='Номер счёта-фактуры'),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('buyer_name', sa.String(length=500), nullable=False),
    sa.Column('buyer_inn', sa.String(length=12), nullable=False),
    sa.Column('buyer_kpp', sa.String(length=9), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('seller_kpp', sa.String(length=9), nullable=True),
    sa.Column('income_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('special_sales_book', sa.Boolean(), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['invoice_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_invoice_drafts_operation_id'), table_name='invoice_drafts')
    op.drop_table('invoice_drafts')
    # ### end Alembic commands ###
