"""add data_load_logs

Revision ID: 4d87c23a3f49
Revises: 3c999bd4b7f1
Create Date: 2026-04-17 09:39:15.303524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d87c23a3f49'
down_revision: Union[str, None] = '3c999bd4b7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_load_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('load_type', sa.Enum('STANDARD', 'BY_DATE', 'BY_ACCOUNT', name='dataloadtype'), nullable=False, comment='Тип загрузки'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCESS', 'ERROR', name='dataloadstatus'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True, comment='Начало периода загрузки'),
    sa.Column('period_end', sa.Date(), nullable=True, comment='Конец периода загрузки'),
    sa.Column('account_number', sa.String(length=25), nullable=True, comment='Номер лицевого счёта'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Логин пользователя'),
    sa.Column('records_loaded', sa.Integer(), nullable=False, comment='Количество загруженных проводок'),
    sa.Column('error_code', sa.Integer(), nullable=False, comment='Код ошибки (0 = нет ошибки)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время начала загрузки'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время окончания загрузки'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_load_logs')
    # ### end Alembic commands ###
