"""add counterparties

Revision ID: 6fff311a1592
Revises: 13afb2b14af4
Create Date: 2026-05-11 20:29:35.588578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fff311a1592'
down_revision: Union[str, None] = '13afb2b14af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False, comment='ИНН'),
    sa.Column('kpp', sa.String(length=9), nullable=True, comment='КПП'),
    sa.Column('full_name', sa.String(length=500), nullable=False, comment='Полное наименование'),
    sa.Column('short_name', sa.String(length=255), nullable=True, comment='Краткое наименование'),
    sa.Column('address', sa.Text(), nullable=True, comment='Адрес'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Телефон'),
    sa.Column('responsible_id', sa.UUID(), nullable=True, comment='Ответственный'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['responsibles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_inn'), 'counterparties', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_inn'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
