"""update invoices model

Revision ID: bfcb60686521
Revises: 3c73d1b244b6
Create Date: 2026-05-12 09:20:28.243400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfcb60686521'
down_revision: Union[str, None] = '3c73d1b244b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_drafts_operation_id', table_name='invoice_drafts')
    op.drop_constraint('invoice_drafts_created_by_fkey', 'invoice_drafts', type_='foreignkey')
    op.drop_column('invoice_drafts', 'currency_code')
    op.drop_column('invoice_drafts', 'branch_code')
    op.drop_column('invoice_drafts', 'buyer_kpp')
    op.drop_column('invoice_drafts', 'vat_amount')
    op.drop_column('invoice_drafts', 'draft_date')
    op.drop_column('invoice_drafts', 'vat_rate')
    op.drop_column('invoice_drafts', 'total_amount')
    op.drop_column('invoice_drafts', 'buyer_inn')
    op.drop_column('invoice_drafts', 'interprice_difference')
    op.drop_column('invoice_drafts', 'created_by')
    op.drop_column('invoice_drafts', 'updated_at')
    op.drop_column('invoice_drafts', 'buyer_address')
    op.drop_column('invoice_drafts', 'buyer_name')
    op.drop_column('invoice_drafts', 'seller_kpp')
    op.drop_column('invoice_drafts', 'operation_id')
    op.drop_column('invoice_drafts', 'special_sales_book')
    op.drop_column('invoice_drafts', 'income_amount')
    op.add_column('invoices', sa.Column('correction_number', sa.String(length=50), nullable=True, comment='Номер корректировки'))
    op.add_column('invoices', sa.Column('payment_document_number', sa.String(length=100), nullable=True, comment='Номер платёжного документа'))
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Дата отправки'))
    op.add_column('invoices', sa.Column('payment_date', sa.Date(), nullable=True, comment='Дата оплаты'))
    op.add_column('invoices', sa.Column('total_with_vat', sa.Numeric(precision=18, scale=2), nullable=False, comment='Итого с НДС'))
    op.add_column('invoices', sa.Column('service_code', sa.String(length=50), nullable=True, comment='Код услуги'))
    op.add_column('invoices', sa.Column('service_name', sa.String(length=500), nullable=True, comment='Наименование услуги'))
    op.add_column('invoices', sa.Column('unit_name', sa.String(length=100), nullable=True, comment='Наименование единицы измерения'))
    op.add_column('invoices', sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True, comment='Количество'))
    op.add_column('invoices', sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True, comment='Цена'))
    op.add_column('invoices', sa.Column('country_code', sa.String(length=3), nullable=True, comment='Код страны'))
    op.add_column('invoices', sa.Column('inter_price_difference', sa.Boolean(), nullable=False, comment='Флаг межценовой разницы'))
    op.add_column('invoices', sa.Column('counterparty_id', sa.UUID(), nullable=True, comment='Контрагент'))
    op.add_column('invoices', sa.Column('branch_id', sa.UUID(), nullable=True, comment='Отделение'))
    op.add_column('invoices', sa.Column('regional_center_id', sa.UUID(), nullable=True, comment='Региональный центр продавца'))
    op.add_column('invoices', sa.Column('confirmed_by_id', sa.UUID(), nullable=True, comment='Кто подтвердил'))
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               comment='Дата счёта-фактуры',
               existing_nullable=False)
    op.alter_column('invoices', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               comment='Код валюты',
               existing_nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='Сумма без НДС',
               existing_nullable=False)
    op.alter_column('invoices', 'vat_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='Сумма НДС',
               existing_nullable=False)
    op.alter_column('invoices', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               comment='Ставка НДС')
    op.alter_column('invoices', 'special_sales_book',
               existing_type=sa.BOOLEAN(),
               comment='Флаг спецкниги продаж',
               existing_nullable=False)
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_draft_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['confirmed_by_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'regional_centers', ['regional_center_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'counterparties', ['counterparty_id'], ['id'])
    op.drop_column('invoices', 'buyer_inn')
    op.drop_column('invoices', 'created_by')
    op.drop_column('invoices', 'branch_code')
    op.drop_column('invoices', 'buyer_kpp')
    op.drop_column('invoices', 'draft_id')
    op.drop_column('invoices', 'buyer_address')
    op.drop_column('invoices', 'buyer_name')
    op.drop_column('invoices', 'seller_kpp')
    op.drop_column('invoices', 'income_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('income_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('seller_kpp', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('buyer_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('draft_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer_kpp', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('branch_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer_inn', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_draft_id_fkey', 'invoices', 'invoice_drafts', ['draft_id'], ['id'])
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'])
    op.alter_column('invoices', 'special_sales_book',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг спецкниги продаж',
               existing_nullable=False)
    op.alter_column('invoices', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               comment=None,
               existing_comment='Ставка НДС')
    op.alter_column('invoices', 'vat_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='Сумма НДС',
               existing_nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='Сумма без НДС',
               existing_nullable=False)
    op.alter_column('invoices', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Код валюты',
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата счёта-фактуры',
               existing_nullable=False)
    op.drop_column('invoices', 'confirmed_by_id')
    op.drop_column('invoices', 'regional_center_id')
    op.drop_column('invoices', 'branch_id')
    op.drop_column('invoices', 'counterparty_id')
    op.drop_column('invoices', 'inter_price_difference')
    op.drop_column('invoices', 'country_code')
    op.drop_column('invoices', 'price')
    op.drop_column('invoices', 'quantity')
    op.drop_column('invoices', 'unit_name')
    op.drop_column('invoices', 'service_name')
    op.drop_column('invoices', 'service_code')
    op.drop_column('invoices', 'total_with_vat')
    op.drop_column('invoices', 'payment_date')
    op.drop_column('invoices', 'sent_at')
    op.drop_column('invoices', 'payment_document_number')
    op.drop_column('invoices', 'correction_number')
    op.add_column('invoice_drafts', sa.Column('income_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False, comment='Сумма комиссии без НДС'))
    op.add_column('invoice_drafts', sa.Column('special_sales_book', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Специальная книга продаж'))
    op.add_column('invoice_drafts', sa.Column('operation_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Ключ связывания с проводками'))
    op.add_column('invoice_drafts', sa.Column('seller_kpp', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('buyer_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('buyer_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('invoice_drafts', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('interprice_difference', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Межценовая разница'))
    op.add_column('invoice_drafts', sa.Column('buyer_inn', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('total_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False, comment='Итого с НДС'))
    op.add_column('invoice_drafts', sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False, comment='Ставка НДС'))
    op.add_column('invoice_drafts', sa.Column('draft_date', sa.DATE(), autoincrement=False, nullable=False, comment='Дата проводки'))
    op.add_column('invoice_drafts', sa.Column('vat_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False, comment='Сумма НДС'))
    op.add_column('invoice_drafts', sa.Column('buyer_kpp', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('branch_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoice_drafts', sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False, comment='Код валюты (810=RUB)'))
    op.create_foreign_key('invoice_drafts_created_by_fkey', 'invoice_drafts', 'users', ['created_by'], ['id'])
    op.create_index('ix_invoice_drafts_operation_id', 'invoice_drafts', ['operation_id'], unique=False)
    # ### end Alembic commands ###
