"""responsible FK to users, drop username full_name

Revision ID: c3788d1fa6e7
Revises: fc19c486769f
Create Date: 2026-05-04 19:43:17.164216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3788d1fa6e7'
down_revision: Union[str, None] = 'fc19c486769f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsibles', sa.Column('user_id', sa.UUID(), nullable=False, comment='Ссылка на пользователя'))
    op.create_foreign_key(None, 'responsibles', 'users', ['user_id'], ['id'])
    op.drop_column('responsibles', 'username')
    op.drop_column('responsibles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsibles', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='ФИО'))
    op.add_column('responsibles', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Логин пользователя'))
    op.drop_constraint(None, 'responsibles', type_='foreignkey')
    op.drop_column('responsibles', 'user_id')
    # ### end Alembic commands ###
