"""add regional_centers, branches, vat_accounts

Revision ID: d80df102553d
Revises: 4d87c23a3f49
Create Date: 2026-04-19 14:53:36.069146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80df102553d'
down_revision: Union[str, None] = '4d87c23a3f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Код регионального центра'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Наименование'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_centers_code'), 'regional_centers', ['code'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Код отделения'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Наименование отделения'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Адрес'),
    sa.Column('inn', sa.String(length=12), nullable=True, comment='ИНН'),
    sa.Column('kpp', sa.String(length=9), nullable=True, comment='КПП'),
    sa.Column('regional_center_id', sa.UUID(), nullable=False, comment='Региональный центр'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_center_id'], ['regional_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_table('vat_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=25), nullable=False, comment='Номер счета по НДС'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Наименование счета'),
    sa.Column('regional_center_id', sa.UUID(), nullable=False, comment='Региональный центр'),
    sa.Column('branch_id', sa.UUID(), nullable=False, comment='Отделение'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['regional_center_id'], ['regional_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_accounts_account_number'), 'vat_accounts', ['account_number'], unique=False)
    op.alter_column('data_load_logs', 'account_number',
               existing_type=sa.VARCHAR(length=25),
               comment='Номер лицевого счета',
               existing_comment='Номер лицевого счёта',
               existing_nullable=True)
    op.alter_column('data_load_logs', 'error_code',
               existing_type=sa.INTEGER(),
               comment='Код ошибки',
               existing_comment='Код ошибки (0 = нет ошибки)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_load_logs', 'error_code',
               existing_type=sa.INTEGER(),
               comment='Код ошибки (0 = нет ошибки)',
               existing_comment='Код ошибки',
               existing_nullable=False)
    op.alter_column('data_load_logs', 'account_number',
               existing_type=sa.VARCHAR(length=25),
               comment='Номер лицевого счёта',
               existing_comment='Номер лицевого счета',
               existing_nullable=True)
    op.drop_index(op.f('ix_vat_accounts_account_number'), table_name='vat_accounts')
    op.drop_table('vat_accounts')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_regional_centers_code'), table_name='regional_centers')
    op.drop_table('regional_centers')
    # ### end Alembic commands ###
