"""add responsibles

Revision ID: fc19c486769f
Revises: fe249c8010e9
Create Date: 2026-04-27 18:20:41.624276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc19c486769f'
down_revision: Union[str, None] = 'fe249c8010e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsibles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Логин пользователя'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='ФИО'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='Отдел'),
    sa.Column('regional_center_id', sa.UUID(), nullable=False, comment='Региональный центр'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_center_id'], ['regional_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibles')
    # ### end Alembic commands ###
