"""add income_accounts

Revision ID: fe249c8010e9
Revises: 3d918cb9c616
Create Date: 2026-04-27 17:30:59.179701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe249c8010e9'
down_revision: Union[str, None] = '3d918cb9c616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=25), nullable=False, comment='Номер счета доходов'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Наименование счета'),
    sa.Column('regional_center_id', sa.UUID(), nullable=False, comment='Региональный центр'),
    sa.Column('branch_id', sa.UUID(), nullable=False, comment='Отделение'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['regional_center_id'], ['regional_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_accounts_account_number'), 'income_accounts', ['account_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_accounts_account_number'), table_name='income_accounts')
    op.drop_table('income_accounts')
    # ### end Alembic commands ###
